#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = firefox

# Random wallpaper with Hyprpaper
exec-once = sh -c "pgrep -x hyprpaper >/dev/null || hyprpaper"

# Notification center
exec-once = sh -c "pgrep -x swaync >/dev/null || swaync"

# Network Manager applet for tray-based network management
exec-once = nm-applet --indicator

# Automatic mounting for USB and removable devices
exec-once = udiskie --tray

# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# GNOME Keyring Daemon
exec-once = dbus-update-activation-environment --all
exec-once = gnome-keyring-daemon --start --components=secrets
