#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# XDG - necesario para que xdg-open y Dolphin encuentren los .desktop
env = XDG_DATA_DIRS,/usr/local/share:/usr/share
env = XDG_CONFIG_DIRS,/etc/xdg
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# Display - XWayland y Wayland
env = DISPLAY,:0
env = WAYLAND_DISPLAY,wayland-1

# Timezone
env = TZ,America/Argentina/Buenos_Aires

# GNOME Keyring
env = GNOME_KEYRING_CONTROL,/run/user/1000/keyring
